package rules;

import pl.gogacz.planner.dto.ReservationRuleContext;
import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;

// --- REGUŁA 1: Brak podróży w czasie ---
rule "Odrzucenie rezerwacji w przeszlosci"
when
    $ctx : ReservationRuleContext( startTime != null, startTime.isBefore(LocalDateTime.now()) )
then
    System.out.println("🤖 DROOLS: Wykryto datę z przeszłości!");
    $ctx.setValid(false);
    $ctx.setRejectionReason("SYSTEM: Nie można rezerwować sprzętu z datą wsteczną.");
end

// --- REGUŁA 2: Odwrócone daty (Koniec przed Startem) ---
rule "Odrzucenie blednych dat"
when
    $ctx : ReservationRuleContext( startTime != null, endTime != null, endTime.isBefore(startTime) )
then
    System.out.println("🤖 DROOLS: Data końca jest przed datą startu!");
    $ctx.setValid(false);
    $ctx.setRejectionReason("SYSTEM: Data zwrotu nie może być wcześniejsza niż data wypożyczenia.");
end

// --- REGUŁA 3: Zbyt długi czas wypożyczenia (np. max 30 dni) ---
rule "Maksymalny czas wypozyczenia 30 dni"
when
    $ctx : ReservationRuleContext( startTime != null, endTime != null, ChronoUnit.DAYS.between(startTime, endTime) > 30 )
then
    System.out.println("🤖 DROOLS: Przekroczono limit 30 dni!");
    $ctx.setValid(false);
    $ctx.setRejectionReason("SYSTEM: Maksymalny czas rezerwacji tego zasobu to 30 dni.");
end