# Nazwa aplikacji
spring.application.name=smart-resource-planner

# Po??czenie z PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5434/planner_db
spring.datasource.username=postgres
spring.datasource.password=planner123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Spring Security - JEDEN LOGIN I HAS?O
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN,USER

# To wymusi na Camundzie stworzenie/aktualizacj? admina przy starcie
camunda.bpm.admin-user.id=admin
camunda.bpm.admin-user.password=admin123
camunda.bpm.filter.create=All Tasks

camunda.bpm.default-serialization-format=application/json