# Nazwa aplikacji
spring.application.name=smart-resource-planner
server.port=8080
spring.jpa.show-sql=true

# Spring Security
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN,USER

# Camunda
camunda.bpm.admin-user.id=admin
camunda.bpm.admin-user.password=admin123
camunda.bpm.filter.create=All Tasks
camunda.bpm.default-serialization-format=application/json

# Poczta
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=bbcaff3d89e863
spring.mail.password=c070c1486843ea
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs